apiVersion: v1
kind: Secret
metadata:
  name: csi-s3-secret
  namespace: kube-system
stringData:
  accessKeyID: "YCAJE4wqh4p3qeqEoZDng59Tk"
  secretAccessKey: "YCMErYzd_J29i_d_GsydE9DJTKaQ3SdlvxsyL7HH"
  endpoint: https://storage.yandexcloud.net
