apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-mysql
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-mysql
rules:
- apiGroups: ["otus.homework"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "delete", "get", "list", "watch"]

- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create", "delete", "get", "list", "watch"]

- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["create", "get", "list", "watch", "delete"]

- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
  
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]

- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]

- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch", "update", "patch"]

- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-mysql
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-mysql
subjects:
- kind: ServiceAccount
  name: sa-mysql
  namespace: default
