apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: app-nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: app-nginx
    spec:
      serviceAccountName: {{ .Values.serviceAccounts.monitoring }}
      nodeSelector:
        env: {{ .Values.nodeSelector.env }}
      volumes:
        - name: sharedvolume
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.claimName }}
        - name: configvolume
          configMap:
            name: {{ .Values.configMapName }}
      initContainers:
        - name: init-container
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "K8s by OTUS. Lesson #7. Homework#6" > /init/index.html
              wget -q -O /init/metrics.html http://kube-state-metrics.kube-system.svc.cluster.local:8080/metrics
          volumeMounts:
            - name: sharedvolume
              mountPath: /init
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.container.port }}
          volumeMounts:
            - name: sharedvolume
              mountPath: /homework
            - name: configvolume
              mountPath: /homework/conf/file
              subPath: file
            - name: configvolume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          lifecycle:
            preStop:
              exec:
                command: ['sh', '-c', 'rm -f /homework/index.html']
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.container.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          {{- end }}
