apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.monitoring }}
  namespace: {{ .Values.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-metrics
rules:
- nonResourceURLs: ["/metrics"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: binding-monitoring-metrics
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccounts.monitoring }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: role-metrics
  apiGroup: rbac.authorization.k8s.io
