apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  namespace: homework
spec:
  type: ClusterIP
  selector:
    app: app-nginx
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000 