apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.persistence.storageClass }}
provisioner: disk-csi-driver.mks.ycloud.io  
parameters:
  type: network-hdd  
reclaimPolicy: Retain
volumeBindingMode: Immediate
