apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring
  namespace: homework
---
apiVersion: rbac.authorization.k8s.io/v1
kind:  ClusterRole
metadata:
  name: role-metrics
  namespace: homework
rules:
   - nonResourceURLs: ["/metrics"]
     verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: binding-monitoring-metrics
  namespace: homework
subjects:
  - kind: ServiceAccount
    name: monitoring
    namespace: homework
roleRef:
  kind: ClusterRole
  name: role-metrics
  apiGroup: rbac.authorization.k8s.io