apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-secrets
  namespace: vault
spec:
  refreshInterval: "10m"
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: otus-cred
  data:
  - secretKey: username
    remoteRef:
      key: otus/cred
      property: username
  - secretKey: password
    remoteRef:
      key: otus/cred
      property: password
