injector:
  enabled: false

server:
  enabled: true
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: false
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "consul" {
        path = "vault"
        address = "consul-server.consul.svc.cluster.local:8500"
      }

      service_registration "kubernetes" {}

ui:
  enabled: true

csi:
  enabled: false
