global:
  logJSON: true
  name: consul 
  image: hashicorp/consul:1.21
  datacenter: dc1
  gossipEncryption:
    autoGenerate: true

client:
  enabled: true

server:
  enabled: true
  replicas: 3
  storage: 200Mi
  disruptionBudget:
    maxUnavailable: 0

ui:
  enabled: true
  service:
    type: ClusterIP

connectInject:
  enabled: false
