apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        env: homework
      volumes:
        - name: sharedvolume
          emptyDir:
            sizeLimit: 10Mi
      initContainers:
        - name: init-container
          image: busybox
          command: ['sh', '-c', 'echo "K8s by OTUS. Lesson #2" > /init/index.html']
          volumeMounts:
            - name: sharedvolume
              mountPath: /init    
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: sharedvolume
              mountPath: /homework
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", 
                          "echo 'server { \
                              listen 8000; \
                              server_name localhost; \
                              location / { \
                                  root /homework; \
                                  index index.html; \
                              } \
                          }' > /etc/nginx/conf.d/default.conf && 
                          service nginx reload"]
            preStop:
              exec:
                command: ['sh', '-c', 'rm -f /homework/index.html']
          readinessProbe:
           exec:
             command: 
              - cat 
              - /homework/index.html
           initialDelaySeconds: 15 
           periodSeconds: 10      
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1