apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-nginx
  template:
    metadata:
      labels:
        app: app-nginx
    spec:
      nodeSelector:
        env: homework
      volumes:
        - name: sharedvolume
          persistentVolumeClaim:
            claimName: pv-homework
        - name: configvolume
          configMap:
            name: confmap-homework 
      initContainers:
        - name: init-container
          image: busybox
          command: ['sh', '-c', 'echo "K8s by OTUS. Lesson #5. Homework#4" > /init/index.html']
          volumeMounts:
            - name: sharedvolume
              mountPath: /init    
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: sharedvolume
              mountPath: /homework
            - name: configvolume
              mountPath: /homework/conf 
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", 
                          "echo 'server { \
                              listen 8000; \
                              server_name localhost; \
                              location / { \
                                  root /homework; \
                                  index index.html; \
                              } \
                          }' > /etc/nginx/conf.d/default.conf && 
                          service nginx reload"]
            preStop:
              exec:
                command: ['sh', '-c', 'rm -f /homework/index.html']
          readinessProbe:
            httpGet:
              path: /index.html
              port: 8000
            initialDelaySeconds: 10 
            periodSeconds: 10      
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1