apiVersion: v1
kind: Pod
metadata:
  name: homework1
  namespace: homework
spec:
  volumes:
    - name: sharedvolume
      emptyDir:
        sizeLimit: 10Mi
  initContainers:
    - name: initcontaner
      image: busybox
      command: ['sh', '-c','echo "K8s by OTUS. Lesson #1" > /init/index.html']
      volumeMounts:
        - name: sharedvolume
          mountPath: /init
  containers:
   - name: nginx
     image: nginx
     ports:
       - containerPort: 8000
     volumeMounts:
       - name: sharedvolume
         mountPath: /homework
     lifecycle:
        postStart:
         exec:
          command: ["/bin/sh", "-c", 
                    "echo 'server { \
                        listen 8000; \
                        server_name localhost; \
                        location / { \
                            root /homework; \
                            index index.html; \
                        } \
                    }' > /etc/nginx/conf.d/default.conf"]
        preStop:
          exec:
            command: ['sh','-c','rm -f /homework/index.html']  
