apiVersion: v1
kind: Pod
metadata:
  name: homework1
  namespace: homework
spec:
  volumes:
    - name: sharedvolume
      emptyDir:
        sizeLimit: 10Mi
  initContainers:
    - name: initcontaner
      image: busybox
      command: ['sh', '-c','echo "Курсы по k8s. Домашнее задание №1" > /init/index.html']
      volumeMounts:
        - name: sharedvolume
          mountPath: /init
  containers:
   - name: nginx
     image: nginx
     ports:
       - containerPort: 8000
     volumeMounts:
       - name: sharedvolume
         mountPath: /homework
     lifecycle:
        preStop:
          exec:
            command: ['sh','-c','rm -f /homework/index.html']  
