apiVersion: v1
kind: Pod
metadata:
  name: homework1
  namespace: homework
spec:
  volumes:
    - name: shared-volume
      emptyDir: {}
  initContainers:
    - name: busybox
      image: busybox
      command:
        - sh
        - -c
        - echo "Курсы по k8s. Домашнее задание №1" > /init/index.html
      volumeMounts:
        - name: shared-volume
          mountPath: /init
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: shared-volume
          mountPath: /homework
      lifecycle:
        preStop:
          exec:
            command:
              - sh
              - -c
              - rm -f /homework/index.html
